# Generated by Django 5.0 on 2024-01-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pin_number',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
