# Generated by Django 5.0 on 2024-01-09 13:07

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=4, prefix='FBN', unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=7, max_length=7, prefix='024', unique=True),
        ),
    ]
