# Generated by Django 5.0 on 2024-01-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_account_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='signatature',
            new_name='signature',
        ),
    ]
