# Generated by Django 5.0 on 2024-01-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_signatature_kyc_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='kyc_confirmed',
        ),
        migrations.RemoveField(
            model_name='account',
            name='kyc_submitted',
        ),
        migrations.AddField(
            model_name='kyc',
            name='kyc_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('in_review', 'In Review'), ('approved', 'Approved'), ('not_approved', 'Not Approved')], default='not_submitted', max_length=100),
        ),
    ]
