# Generated by Django 5.0 on 2024-01-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_account_kyc_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='identity_image_back',
            field=models.ImageField(upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='identity_image_front',
            field=models.ImageField(upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='passport',
            field=models.ImageField(upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='signature',
            field=models.ImageField(upload_to='kyc'),
        ),
    ]
