# Generated by Django 5.0 on 2024-01-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_kyc_identity_image_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='email_address',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
