# Generated by Django 5.0 on 2024-01-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_kyc_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='email_address',
        ),
    ]
