# Generated by Django 5.0 on 2024-01-09 18:01

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_kyc_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=7, prefix='FBN', unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=7, max_length=10, prefix='024', unique=True),
        ),
    ]
