# Generated by Django 5.0 on 2024-01-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_account_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pin_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
