# Generated by Django 5.0 on 2024-01-10 13:24

import django.db.models.deletion
import shortuuid.django_fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_account_pin_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='address',
            field=models.TextField(max_length=800),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('transaction_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=7, max_length=10, prefix='TRN', unique=True)),
                ('description', models.CharField(max_length=500)),
                ('user_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('transaction_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient', to='account.account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
