# Generated by Django 5.0 on 2024-01-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_account_account_name_alter_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_image',
            field=models.ImageField(null=True, upload_to='account'),
        ),
    ]
