# Generated by Django 5.0 on 2024-01-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_transaction_tranaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_fee',
        ),
        migrations.AddField(
            model_name='transaction',
            name='tranaction_fee',
            field=models.CharField(choices=[('cash_transfer', 50), ('cash_received', 0), ('paid_request', 0), ('payment_received', 0)], max_length=100, null=True),
        ),
    ]
