# Generated by Django 5.0 on 2024-01-10 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_transaction_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user_amount',
            new_name='intended_amount',
        ),
    ]
