# Generated by Django 5.0 on 2024-01-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_transaction_account_alter_transaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='tranaction_fee',
            new_name='transaction_fee',
        ),
    ]
