# Generated by Django 5.0 on 2024-01-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_rename_tranaction_fee_transaction_transaction_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_id',
            new_name='transaction_number',
        ),
    ]
