# Generated by Django 5.0 on 2024-01-11 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_account_account_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='intended_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='recipient',
            new_name='receiver_account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='account',
            new_name='sender_account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_number',
            new_name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_fee',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
