# Generated by Django 5.0 on 2024-01-11 10:45

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_remove_transaction_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=10, prefix='TRN', unique=True),
        ),
    ]
