# Generated by Django 5.0 on 2024-01-11 12:38

import django.db.models.deletion
import shortuuid.django_fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('charge_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=10, prefix='TRN', unique=True)),
                ('transaction_type', models.CharField(max_length=500)),
                ('fee', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.chargemanager'),
        ),
    ]
