# Generated by Django 5.0 on 2024-01-11 12:42

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_chargemanager_transaction_transaction_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargemanager',
            name='charge_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=20, prefix='FEE', unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=20, prefix='TRN', unique=True),
        ),
    ]
