# Generated by Django 5.0 on 2024-01-11 15:40

import django.db.models.deletion
import shortuuid.django_fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_usertransactionmanager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('request_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=20, prefix='RQ', unique=True)),
                ('description', models.CharField(max_length=500)),
                ('payment_due_by', models.DateTimeField(blank=True, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('proof_doc1', models.ImageField(blank=True, null=True, upload_to='request')),
                ('proof_doc2', models.ImageField(blank=True, null=True, upload_to='request')),
                ('proof_doc3', models.ImageField(blank=True, null=True, upload_to='request')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('receiver_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to='account.account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('sender_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.account')),
            ],
        ),
    ]
