# Generated by Django 5.0 on 2024-01-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='action',
            field=models.CharField(choices=[('settle', 'Settled'), ('cancel', 'Cancelled'), ('processing', 'Processing'), ('decline', 'Declined')], max_length=100, null=True),
        ),
    ]
