# Generated by Django 5.0 on 2024-01-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_paymentrequest_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='action',
            new_name='status',
        ),
    ]
