# Generated by Django 5.0 on 2024-01-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_alter_paymentrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('settled', 'Settled'), ('cancelled', 'Cancelled'), ('processing', 'Processing'), ('sent', 'sent'), ('declined', 'Declined')], max_length=100, null=True),
        ),
    ]
