# Generated by Django 5.0 on 2024-01-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_alter_paymentrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='proof_doc1',
            field=models.FileField(blank=True, null=True, upload_to='request'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='proof_doc2',
            field=models.FileField(blank=True, null=True, upload_to='request'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='proof_doc3',
            field=models.FileField(blank=True, null=True, upload_to='request'),
        ),
    ]
