# Generated by Django 5.0 on 2024-01-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_alter_paymentrequest_proof_doc1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('settled', 'Settled'), ('cancelled', 'Cancelled'), ('processing', 'Processing'), ('request', 'request'), ('declined', 'Declined')], max_length=100, null=True),
        ),
    ]
