# Generated by Django 5.0 on 2024-01-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_alter_paymentrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kyc',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='paymentrequest',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='kyc',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
