# Generated by Django 5.0 on 2024-01-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_alter_kyc_options_alter_paymentrequest_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTransactionManager',
        ),
    ]
