# Generated by Django 5.0 on 2024-01-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_userrecentmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecentmanager',
            name='request_accounts',
            field=models.ManyToManyField(null=True, related_name='request_account', to='account.account'),
        ),
        migrations.AddField(
            model_name='userrecentmanager',
            name='transaction_accounts',
            field=models.ManyToManyField(null=True, to='account.account'),
        ),
    ]
