# Generated by Django 5.0 on 2024-01-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_userrecentmanager_request_accounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecentmanager',
            name='request_accounts',
            field=models.ManyToManyField(related_name='request_account', to='account.account'),
        ),
        migrations.AlterField(
            model_name='userrecentmanager',
            name='transaction_accounts',
            field=models.ManyToManyField(to='account.account'),
        ),
    ]
