# Generated by Django 5.0 on 2024-01-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('cash_transfer', 'Cash Transfer'), ('cash_received', 'Cash Received'), ('paid_request', 'Paid Request'), ('payment_received', 'Payment Received')], max_length=100, null=True),
        ),
    ]
