# Generated by Django 5.0 on 2024-01-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_notification_transaction_alter_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='transaction',
        ),
    ]
