# Generated by Django 5.0 on 2024-01-17 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.account'),
        ),
    ]
