# Generated by Django 5.0 on 2024-01-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_alter_creditcard_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcard',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='creditcard',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('cash_transfer', 'Cash Transfer'), ('cash_received', 'Cash Received'), ('paid_request', 'Paid Request'), ('payment_received', 'Payment Received'), ('card_purchase', 'Card Purchase')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tranaction_type',
            field=models.CharField(choices=[('cash_transfer', 'Cash Transfer'), ('cash_received', 'Cash Received'), ('paid_request', 'Paid Request'), ('payment_received', 'Payment Received'), ('card_purchase', 'Card Purchase')], max_length=100, null=True),
        ),
    ]
