# Generated by Django 5.0 on 2024-01-17 14:50

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_alter_creditcard_account_alter_creditcard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='card_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=7, null=True, prefix='CR', unique=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=18, max_length=18, prefix='85', unique=True),
        ),
    ]
