# Generated by Django 5.0 on 2024-03-15 11:41

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0058_creditcard_card_code_alter_creditcard_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=7, prefix='CR', unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('cash_transfer', 'Cash Transfer'), ('cash_received', 'Cash Received'), ('paid_request', 'Paid Request'), ('payment_received', 'Payment Received'), ('card_purchase', 'Card Purchase'), ('card_funding', 'Card Funding'), ('card_withdrawal', 'Card Withdrawal')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tranaction_type',
            field=models.CharField(choices=[('cash_transfer', 'Cash Transfer'), ('cash_received', 'Cash Received'), ('paid_request', 'Paid Request'), ('payment_received', 'Payment Received'), ('card_purchase', 'Card Purchase'), ('card_funding', 'Card Funding'), ('card_withdrawal', 'Card Withdrawal')], max_length=100, null=True),
        ),
    ]
